SELECT
  STG.VENDOR_ID,
  STG.VENDOR_NAME,
  COUNT(*)                                                            AS INVOICES_SUBMITTED,
  SUM(CASE WHEN STG.PROCESS_STATUS = 'SUCCESS' THEN 1 ELSE 0 END)    AS INVOICES_APPROVED,
  SUM(CASE WHEN STG.PROCESS_STATUS = 'ERROR'   THEN 1 ELSE 0 END)    AS INVOICES_REJECTED,
  TO_CHAR(
    SUM(CASE WHEN STG.PROCESS_STATUS = 'SUCCESS' THEN STG.AMOUNT ELSE 0 END),
    '$999,999,999.00'
  )                                                                   AS APPROVED_AMOUNT,
  TO_CHAR(
    SUM(CASE WHEN STG.PROCESS_STATUS = 'ERROR' THEN STG.AMOUNT ELSE 0 END),
    '$999,999,999.00'
  )                                                                   AS REJECTED_AMOUNT
FROM
  XX_FIN_STG STG
WHERE
  STG.BATCH_ID = 'BATCH-2026-001'
GROUP BY
  STG.VENDOR_ID,
  STG.VENDOR_NAME
ORDER BY
  STG.VENDOR_NAME;
 
 
